//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Data.Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientPK { get; set; }
        public string NationalCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> GenderTypeCode { get; set; }
        public string Mobile { get; set; }
    
        public virtual Patient Patient1 { get; set; }
        public virtual Patient Patient2 { get; set; }
    }
}
